name: Deploy To Azure Web App

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install Depencencies
        run: npm install
      - name: Deploy To Azure Ap Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: devops-ci-cd-matias
          publish-profile: $ {{secrets.AZURE_PUBLISH_PROFILE}}
          package: ./NewApplication